package_name = "com.testreactnativeproject"
json_key_file_path = "./google-service-account-key.json"
gradle_file_path = "./app/build.gradle"
slack_weebhook_url = ENV["SLACK_WEBHOOK_URL"]

default_platform(:android)

platform :android do
  desc "Build and deploy to internal track"
  lane :internal do
    
    # Clean and bundle the release build
    gradle(
      task: "clean bundleRelease",
      gradle_path: "./gradlew"
    )

    # Upload the app to Google Play Store
    upload_to_play_store(
      track: "beta",
      aab: "app/build/outputs/bundle/release/app-release.aab",
      json_key: json_key_file_path,
      package_name: package_name          
    )

    # Notify via Slack
    slack(
      slack_url: slack_weebhook_url,
      message: "Android : Build #{current_build_number} is available for Open Testing",
      channel: "#whenn-app",
      default_payloads: [],
      success: true,
      payload: {
        'Build Date' => Time.now,
        'Build Number' => current_build_number
      }
    )
  end
end
