name: android-deployment

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    continue-on-error: false

    steps:
      - uses: actions/checkout@v3  # Use the latest version

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.3

      - name: Install Ruby Dependencies
        run: |
          cd android
          bundle install

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Node.js Dependencies
        run: |
          cd android
          npm install

      # Add Java 17 setup step
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Create the Google Service Account Key JSON file from the secret
      - name: Setup Google Service Account Key
        run: |
          echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}" > android/google-service-account-key.json

      - name: Build and deploy
        run: |
          cd android
          export NODE_OPTIONS=--openssl-legacy-provider
          bundle exec fastlane android internal
