name: android-deployment  # Set your desired name here

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    continue-on-error: false

    steps:
      - uses: actions/checkout@v2  # Use a specific version for checkout

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.4

      - name: Install Dependencies
        run: |
          cd android
          bundle install

      - name: Setup dependencies
        run: |
          printf '%s\n' "${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}" > android/google-service-account-key.json
          printf '%s\n' "${{ secrets.ANDROID_SIGNING_KEY }}" > my-upload-key.keystore.asc
          gpg --batch --passphrase "${{ secrets.ANDROID_SIGNING_KEY_PASSPHRASE }}" --decrypt my-upload-key.keystore.asc > android/app/my-upload-key.keystore

      - name: Check Decrypted Key
        run: |
          ls -l android/app/
          # Optionally check the contents of the decrypted keystore file
          # echo "Contents of the keystore (for debugging purposes):"
          # cat android/app/my-upload-key.keystore  # Comment out to avoid logging sensitive data

      - name: Build and deploy
        run: |
          npm install
          export NODE_OPTIONS=--openssl-legacy-provider
          cd android
          bundle exec fastlane android internal
