name: android-deployment  # Set your desired name here

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    continue-on-error: false

    steps:
      - uses: actions/checkout@master

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.3

      - name: Install Ruby Dependencies
        run: |
          cd android
          bundle install

      - name: Setup Google Service Account Key
        run: |
          echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}' > android/google-service-account-key.json

      - name: Build and deploy
        run: |
          cd android
          npm install
          export NODE_OPTIONS=--openssl-legacy-provider
          bundle exec fastlane android internal
